---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-repo
  namespace: default
spec:
  interval: 5m0s
  timeout: 60s
  url: https://github.com/cloudoperators/greenhouse
  ref:
    # renovate: datasource=github-tags depName=cloudoperators/greenhouse
    tag: "v0.0.1-alpha.1"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kustomize
  namespace: default
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-repo
  path: "./flux/install"
  prune: true
  timeout: 1m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: helm-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: notification-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: source-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: image-automation-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-system
